### PR TITLE
Propose new feature

### PR DESCRIPTION
**Pull request by skyeeiskowitz**
Propose new feature: be56fc9a_d548_4dc6_afc1_9dd23328eb8b
Submitted by user: skyeeiskowitz

--
Pull request automatically created by ballet-assemble

### CODE REVIEW

**Comment by micahjsmith** [comment]
hey @skyeeiskowitz thanks for submitting! I think this is a great idea for a feature

to figure out why the PR is failing, I looked into the CI logs I see:

```
  File "/home/travis/build/HDI-Project/ballet-fragile-families/src/fragile_families/features/contrib/user_skyeeiskowitz/feature_be56fc9a_d548_4dc6_afc1_9dd23328eb8b.py", line 66, in <module>

    feature = Feature(input, transformer, name=name, description=description)

NameError: name 'transformer' is not defined
```

seems like there is a typo somewhere?

couple other comments I had:
* in the transformer, if you are taking the sum of *all* columns, you can do `lambda df: df.sum(axis=1)` to save some typing
* after the first two steps in the transformer (value replacing and sum), are there still any missing values? I'm trying to think through the effect of the imputation step. Often in the FFC data, the missing values are coded as negative values (i.e. `-9` is `not in wave`), so by replacing those negative values with 0, you may have already addressed all possible missing values. if you want to leave those as missing but impute them later, you could replace the negative values with NaNs instead of 0. can also do `lambda df: df.where(df >= 0, np.nan)` to replace all values <0 with NaN (see [where](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.where.html?highlight=where#pandas.DataFrame.where)).

**Comment by skyeeiskowitz** [comment]
Thank you @micahjsmith, sorry I hadn't realized the PR wasn't successful. How do I make fixes to my code in Assemble? Each time I launch it, it is the original notebook.

**Comment by micahjsmith** [comment]
No worries @skyeeiskowitz, this is missing functionality in Assemble on two fronts (can't see what happened with a PR and can't edit a feature in submission)

1. Easiest solution: copy the feature definition from this PR into a new Assemble session, make fixes, submit a new PR, and close this one
2. Alternate solution: push additional commits to this PR using the [local feature development workflow](https://ballet.github.io/ballet/contributor_guide.html#local-feature-development-workflow). 
    * cloning your fork (`git clone https://github.com/skyeeiskowitz/ballet-fragile-families.git`)
    * checkout this branch (`git checkout -t origin/submit-feature-be56fc9a-d548-4dc6-afc1-9dd23328eb8b`)
    * edit the file and commit changes
    * push commits back to the branch on your fork (`git push`)

**Comment by skyeeiskowitz** [comment]
Got it, thanks..closing this PR.

**Pull request closed without merging**
